config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/biografia',to: 'pages#biografia'
  get 'pages/carrera', to:'pages#carrera'
  get 'pages/videos', to:'pages#videos'
  get 'pages/contact', to:'pages#contact'
  resources :letters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/letter.rb
class Letter < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  def index
    @letters = Letter.all
  end

  def show
    @letter = Letter.find(params[:id])
  end

  def new
    @letter = Letter.new
  end

  def create
    @letter = Letter.create(letter_params)
    @letter.save
    redirect_to root_path
  end

  def destroy
    @album = Album.find(params[:id]).destroy
    redirect_to root_path
    authorize @album
  end

  private

  def letter_params
    params.require(:letter).permit(:name, :email, :message)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :carrera, :biografia, :videos, :contact]

  def home
  end

  def carrera
  end

  def biografia
  end

  def videos
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Miryam Roper</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
</head>
<body class="Site">
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <main class="Site-content">
    <%= yield %>
  </main>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/letters/index.html.erb
<div class="">
  <div class="container">
    <h1>Letters</h1>
    <% @letters.each do |letter|  %>
    <div class="col-xs-12">
    <%= link_to letter_path(letter) do %>
    <p><%= letter.name%> || <%= letter.email%></i></p>
    <%end%>
    </div>
    <% end %>
  </div>
</div>

app/views/letters/new.html.erb
<br>
<br>
<br>
<div class="about">
 <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 text-center padded frame">
      <%= image_tag("mr-id.png")%>
    </div>
    <div class="col-xs-12 col-sm-6">
      <h3>Contact me</h3>
      <%= simple_form_for @letter do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>
      <%= f.input :message %>
      <%= f.button :submit,class: "btn btn-info",style: "border-radius: 50px;" %>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
</div>

app/views/letters/show.html.erb
<div class="pad">
  <div class="container">
    <h3>Mensage Nuevo</h3>
    <div class="col-xs-12">
    <h4><%= @letter.name%></h4>
    <h4><%= @letter.email%></h4>
    <p><%= @letter.message%></p>
    </div>
  </div>
</div>

app/views/pages/biografia.html.erb
<div class="banner" style="background-image: url('<%= image_path('bio.png')%> ');background-position: center;  ">
  <div class="banner-content">
    <h1>Miryam Roper</h1>
    <p class="paint"">ATLETA OLÍMPICA</p>
  </div>
</div>
<div class="box1">
  <div class="container ">
    <div class="row">
      <br>
      <div class="col-xs-12" style="text-align: justify;">
        <p>
         Miryam Roper es una judoka olímpica de 35 años, de origen alemán y panameño.
         Miryam tiene sus inicios en judo a los 7 años de edad, cuando su papá decidió llevarla a tomar clases de judo. Desde entonces, su carrera se fue desarrollando entre viajes desde el pueblo donde vivía con su familia hasta el lugar donde tenía su entrenamiento.
       </p>
       <p>
        A sus 25 años de edad, Miryam fue seleccionada para  formar parte del grupo élite de la selección nacional de judo de Alemania. De la misma manera, el Club Bayern le ofreció ser parte de este mundialmente renombrado club.En el año 2013, con 31 años de edad, Miryam logró coronarse como la #1 del mundo en los Juegos Mundiales de Judo. Ha participado en dos juegos olímpicos con la Selección de Judo de Alemania: Londres 2012 y Río de Janeiro 2016.
      </p>
      <p>
        En el año 2017, Miryam decide representar a Panamá, su otra patria, teniendo a su vez,  grandes desafíos. Pero, esto no impidió que lograra la primera medalla de oro para Panamá en una competencia de Judo, seguido de una medalla de plata en Cancún, y el quinto lugar en los Juegos Mundiales de Judo.
      </p>
      <p>
        Miryam es una atleta sin límites, su tenacidad, persistencia, y sobre todo, su determinada resiliencia, son valores destacados por entrenadores, compañeros, familiares y espectadores.
      </p>
      <p>
        Actualmente,  Miryam es la judoka #4 del mundo en el Ranking Mundial de Judo de -57 kgs. Siendo este un logro que muy pocos esperaban que lograra debido a su edad. Su siguiente desafío es llegar a las Olimpiadas 2020, en donde dejará todo para conseguir lo que nunca antes ha sido logrado: una medalla para Panamá.
      </p>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>
</div>
</div>
<div class="box2">
  <div class="container padded">
    <div class="row">
      <div class=" col-xs-12 text-center">
        <h3>PASIÓN</h3>
        <h4>Cuando estoy en el tatami me siento en mi hogar, es mi elemento.</h4>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12" style="text-align: justify;">
        <p>
         El judo es un deporte completo donde tienes que estar física y mentalmente fuerte, en un combate honesto, uno a uno. Me fascina porque siempre tengo algo que aprender. Cada acción tiene una reacción. En cualquier momento tu oponente puede hacer un movimiento y hacerte caer, así que siempre hay un reto que resolver.
       </p>
       <p>
         Lo que también amo del judo es que somos como una familia. He ganado muchas amistades por todo el mundo. No importa de dónde eres, tus creencias, tus orígenes o cuánto ganas, todos hablamos Judo. Después de una competencia entrenamos juntos y varias veces al año nos encontramos en entrenamientos donde competimos, sentimos las estrategias del otro y luego somos oponentes. Podría sonar raro, pero es uno de los principios básicos del judo: ayudarte a ti mismo y a los demás de forma tal que todos mejoren.
       </p>
       <div class>
        <br>
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo2" style="border-radius: 50px;">Seguir Leyendo</button>
      </div>
      <div id="demo2" class="collapse">
        <br>
        <br>
        <p>
         Por supuesto que también se trata de ganar y eso me encanta. Estoy trabajando duro para lograrlo. Más que eso el judo enseña valores que te ayudan en todos los aspectos de la vida. Por ejemplo, en el saludo antes y después de competir se demuestra respeto y reconocimiento por el esfuerzo del contrincante.
         <br>
         Soy afortunada que mis padres hayan deseado que sus hijos practicaran judo, porque necesitábamos gastar mucha energía, yo en particular. Necesitábamos hacer deportes y movimiento. Con el judo me enamoré a primera vista. No todo el mundo puede decir que le apasiona algo y en esto yo descubrí mucho de lo mío.
       </p>
       <p>
        Mi sueño de niña era participar en los Juegos Olímpicos. Al entrenar duro, ganando y perdiendo he marcado mi meta para ganar una medalla olímpica. Me siento motivada por eso aunque algunas personas habrían desistido después de tener experiencias como la mía. Sin embargo me encanta competir y tengo fe en alcanzar esa última meta porque es algo que aún me queda por hacer.
      </p>
      <p>
        Representar el país de mi padre, compartir mi pasión por el judo y el deporte en Panamá también es importante para mí. Expresar mi panameñidad a través de lo que amo me hace sentir completa. Traer una medalla olímpica a mi segunda patria sería un sueño hecho realidad. Quiero demostrar al mundo y especialmente a la juventud que nada es imposible si crees en ti mismo y trabajas duro. Aunque necesites algo de suerte.
      </p>
    </div>
  </div>
</div>
</div>
<br>
<br>
<br>

app/views/pages/carrera.html.erb
<br>
<br>
<br>
<div class="container">
  <h2>CARRERA</h2>
  <br>
  <ul class="nav nav-tabs time-line">
    <li class="active"><a data-toggle="tab" href="#home">2017</a></li>
    <li><a data-toggle="tab" href="#menu1">2016</a></li>
    <li><a data-toggle="tab" href="#menu2">2015</a></li>
    <li><a data-toggle="tab" href="#menu3">2014</a></li>
    <li><a data-toggle="tab" href="#menu4">2013</a></li>
    <li><a data-toggle="tab" href="#menu5">2012</a></li>
    <li><a data-toggle="tab" href="#menu6">2011</a></li>
    <li><a data-toggle="tab" href="#menu7">2010</a></li>
    <li><a data-toggle="tab" href="#menu8">2009</a></li>
    <li><a data-toggle="tab" href="#menu9">2008</a></li>
    <li><a data-toggle="tab" href="#menu10">2007</a></li>
  </ul>
</div>
  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <div class="card" style="background-image:url('<%= image_path('2017.png')%>');background-position: center;">
        <div class="space">
        <p> 5. PAN AMERICAN CHAMPIONSHIPS PANAMA </p>
        <p>1. Medalla de Oro GRAND SLAM en Ekaterinburg</p>
        <p>2. Cancún Grand Prix Medalla de plata - Mexico</p>
        <p>5. World Championships Budapest Hungría</p>
        </div>
    </div>
  </div>
  <div id="menu1" class="tab-pane">
    <div class="card" style="background-image:url('<%= image_path('2016.png')%>');background-position: center;">
      <div class ="space">
        <p>2. Golden League women Grozny ECC U57 </p>
        <p>Participation Olympic Games Rio de Janeiro </p>
        <p>5. Grand Slam Baku GSL U57</p>
        <p>7. European Championships Kazan ECh U57 </p>
        <p>3. Grand Prix Samsun GP U57 </p>
        <p>3. Grand Prix Tbilisi GP U57 </p>
        <p>7. Grand Prix Havana GP U57 </p>
      </div>
    </div>
  </div>
  <div id="menu2" class="tab-pane fade">
    <div class="card" style="background-image:url('<%= image_path('2015.png')%>');background-position: center;">
      <br>
        <p>5. Grand Slam Tokyo GSL U57</p>
        <p>2. Grand Prix Qingdao GP U57</p>
        <p>7. Grand Slam Paris GSL U57</p>
        <p>3. World Team Championships Astana WTC U57</p>
        <p>2. European Games Baku teams ETC U57</p>
        <p>3. European Games Baku ECh U57</p>
        <p>3. Grand Slam Baku GSL U57</p>
        <p>3. Grand Prix Tbilisi GP U57</p>
        <p>1. German Championships Bonn NC U57</p>
    </div>
  </div>
  <div id="menu3" class="tab-pane fade">
    <div class="card" style="background-image:url('<%= image_path('2014.png')%>');background-position: center;">
      <br>
        <p>7. Grand Prix Jeju GP U57</p>
        <p>1. Grand Prix Qingdao GP U57</p>
        <p>3. World Team Championships Chelyabinsk WTC U57</p>
        <p>5. Grand Prix Havana GP U57</p>
        <p>2. European Team Championships Montpellier ETC U57</p>
        <p>2. European Championships Montpellier ECh U57 </p>
        <p>2. Grand Prix Samsun GP U57 </p>
        <p>5. Grand Prix Düsseldorf GP U57</p>
    </div>
  </div>
  <div id="menu4" class="tab-pane fade">
    <div class="card" style="background-image:url('<%= image_path('2013.png')%>');background-position: center;">
        <br>
        <p>1. IJF World Ranking Leader U57 2013 </p>
        <p>1. European Club Championships women ECC U57 </p>
        <p>1. Grand Prix Abu Dhabi GP U57 </p>
        <p>1. Grand Prix Rijeka GP U57 </p>
        <p>3. World Championships Rio de Janeiro WCh U57 </p>
        <p>1. IJF Grand Slam Moscow GSL U57 </p>
        <p>3. Grand Prix Miami GP U57 </p>
        <p>1. IJF Grand Slam Baku GSL U57 <p>
    </div>
  </div>
  <div id="menu5" class="tab-pane fade">
    <div class="card" style="background-image:url('<%= image_path('2012.png')%>');background-position: center;">
      <div class ="space">
        <p>3. World Cup Istanbul WCup U57</p>
        <p>Participation Olympic Games London </p>
        <p>3. European Team Championships Chelyabinsk ETC U57 </p>
        <p>3. European Championships Chelyabinsk ECh U57 </p>
        <p>2. World Cup Budapest WCup U57 </p>
        <p>5. Grand Slam Paris GSL U57 </p>
        <p>1. World Cup Sofia WCup U57</p>
      </div>
    </div>
  </div>
  <div id="menu6" class="tab-pane fade">
    <div class="card" style="background-image:url('<%= image_path('2011.png')%>');background-position: center;">
      <div class ="space">
      <p>5. Grand Prix Abu Dhabi GP U57 </p>
       <p> 5. World Championships Paris WCh U57 </p>
        <p>2. PJC World Cup Miami WCup U57 </p>
        <p>2. European Team Championships Istanbul ETC U57 </p>
        <p>7. World Cup Prague WCup U57 </p>
        <p>5. Grand Prix Düsseldorf GP U57 </p>
        <p>1. World Cup Sofia WCup U57 </p>
        <p>2. German Championships Ettlingen NC U57</p>
      </div>
    </div>
  </div>
  <div id="menu7" class="tab-pane fade">
    <div class="card" style="background-image:url('<%= image_path('2010.png')%>');background-position: center;">
      <div class ="space">
        <p>5. Grand Prix Abu Dhabi GP U57 </p>
        <p>2. World Team Championships Antalya WTC U57</p>
        <p>5. World Cup Birmingham WCup U57 </p>
        <p>5. World Cup Tallinn WCup U57 </p>
        <p>3. World Cup Bucharest WCup U57</p>
        <p>2. IJF World Cup Cairo WCup U57</p>
        <p>3. Grand Prix Tunis GP U57</p>
      </div>
    </div>
  </div>
  <div id="menu8" class="tab-pane fade">
    <div class="card" style="background-image:url('<%= image_path('2009.png')%>');background-position: center;">
      <div class ="space">
        <p>3. GB World Cup Birmingham WCup U57</p>
       <p>3. German Open Sindelfingen ECup U57</p>
      </div>
    </div>
  </div>
  <div id="menu9" class="tab-pane fade">
    <div class="card" style="background-image:url('<%= image_path('2008.png')%>');background-position: center;">
      <div class ="space">
        <p>3. World Championships Teams Tokyo WTC U57</p>
        <p>2. German Open Braunschweig ECup U57</p>
      </div>
    </div>
  </div>
  <div id="menu10" class="tab-pane fade">
    <div class="card" style="background-image:url('<%= image_path('2007.png')%>');background-position: center;">
      <p class ="space">3. Super World Cup Hamburg SWC U57</p>
    </div>
  </div>
</div>
</div>

app/views/pages/contact.html.erb
<br>
<br>
<br>
<div class="about">
 <div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 text-center frame padded">
      <%= image_tag("mr-id.png")%>
    </div>
    <div class="col-xs-12 col-sm-6">
     <ul class="list-unstyled padded">
      <h3>Miryam Roper</h3>
      <h4>miryamromperpanama@gmail.com</h4>
      <h4>@miryamromper</h4>
      <h4>Entrevistas y prensa: </h4>
      <h4>prensa@puntobohemio.com</h4>
      <h4>+507 62838609</h4>
      <%= link_to "Escríbeme", new_letter_path, class: "btn btn-info",style: "border-radius: 50px;"%>
    </ul>
  </div>
</div>
</div>
<br>
<br>
</div>

app/views/pages/home.html.erb
<div class="banner padded" style="background-image: url('<%= image_path('banner.jpg')%> ');background-position: center;  ">
  <div class="banner-content">
    <h1>Miryam Roper</h1>
    <p>ATLETA OLÍMPICA</p>
    <%= link_to "  Biografia  ", pages_biografia_path, class: "btn btn-info",style: "border-radius: 50px;"%>
  </div>
</div>
<div class="padded">
  <div class="intro"">
    <div class="container">
      <div class="row text-center">
        <h2>CARRERA</h2>
        <br>
        <br>
        <div class="col-sm-4 text-center">
          <div class="push">
            <h1>+ 300</h1>
            <br>
            <p>Peleas</p>
          </div>
        </div>
        <div class="col-sm-4 text-center">
          <div class="push">
            <h1>+ 80</h1>
            <br>
            <p>Competiciones</p>
          </div>
        </div>
        <div class="col-sm-4 text-center">
          <div class="push">
          <h1>+15,000h</h1>
          <br>
          <p>Entrenamiento</p>
        </div>
        </div>
      </div>
    </div>

    <div class="text-center pad" style="padding-top: 70px">
     <%= link_to "Ver", pages_carrera_path, class: "btn btn-info",style: "border-radius: 50px;"%>
   </div>
 </div>
 <div class="">
  <div class="box">
    <div class="container">
      <div class="row">
        <div class ="text-center">
          <div class="col-xs-12">
            <hr>
            <h2>MIRYAM ROPER - SEVARA NISHANBAYEVA</h2>
            <h4 class="paint"> WORLD CHAMPIONSHIPS BUDAPEST 2017</h4>
            <h6>28 Aug 2017</h6>
            <br>
            <blockquote class="embedly-card"><h4><a href="https://www.youtube.com/watch?time_continue=9&v=iGu8zcXNKZ0">wc sen2017 w 0057 0039</a></h4><p>Uploaded by Judo on 2017-08-30.</p></blockquote>
            <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
            <hr>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/videos.html.erb
<h2 class = "padded text-center">VIDEOS</h2>
<div class="padded">
  <div class="wrapped">
    <div class="container">
      <div class="row">
        <div class ="text-center">
          <div class="col-xs-12">
            <hr>
            <h3>MIRYAM ROPER - SEVARA NISHANBAYEVA</h3>
            <h5>WORLD CHAMPIONSHIPS BUDAPEST 2017</h5>
            <h6>28 Aug 2017</h6>
              <blockquote class="embedly-card"><h4><a href="https://www.youtube.com/watch?time_continue=9&v=iGu8zcXNKZ0">wc sen2017 w 0057 0039</a></h4><p>Uploaded by Judo on 2017-08-30.</p></blockquote>
              <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
          </div>
          <div class="col-xs-12">
            <hr>
            <h3>MIRYAM ROPER -  <br>AMELIA FULGENTES</h3>
            <h5>GRAND PRIX CANCUN 2017</h5>
            <h6>16 Jun 2017</h6>
              <blockquote class="embedly-card"><h4><a href="https://www.youtube.com/watch?v=XXkXY1zIn4I">gp mex2017 w 0057 0009</a></h4><p>Uploaded by Judo on 2017-06-16.</p></blockquote>
              <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<div class="wrapped">
  <div class="container">
    <div class="row">
      <div class ="text-center">
        <div class="col-xs-12">
          <hr>
          <h3>MIRYAM ROPER - IRINA ZABLUDINA</h3>
          <h5>GRAND SLAM EKATERINBURG 2017</h5>
          <h6>20 May 2017</h6>
          <br>
          <br>
          <blockquote class="embedly-card"><h4><a href="https://www.youtube.com/watch?v=t4keSx8uWI0">gs rus2017 w 0057 0026</a></h4><p>Uploaded by Judo on 2017-05-20.</p></blockquote>
          <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
        </div>
        <div class="col-xs-12">
          <hr>
          <h3>MIRYAM ROPER - RAFAELA SILVA</h3>
          <h5>GRAND PRIX HAVANA 2016</h5>
          <h6>22 Jan 2016</h6>
          <br>
          <br>
          <blockquote class="embedly-card"><h4><a href="https://www.youtube.com/watch?v=1WwqtD_LUrI">gp_cub2016_w_0057_0026</a></h4><p>Uploaded by Judo on 2016-01-23.</p></blockquote>
          <script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="text-center">
  <a href="http://www.judoinside.com/judoka/15886/Miryam_Roper/judo-videos" class="btn btn-info" style="border-radius: 50px;">
    <h6>
      Ver más
    </h6>
  </a>
</div>
<br>
<br>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li><a href="https://www.instagram.com/miryamroper/"><i class="fa fa-instagram"></i></a></li>
          <li><a href="https://www.facebook.com/miryamroper/?hc_ref=SEARCH"><i class="fa fa-facebook"></i></a></li>
          <li><a href="https://www.twitter.com/miryamroper/""><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-8 text-right">
        <%= image_tag "logo.png" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_head.html.erb
<div class="head navbar-wagon-fixed" style="background-color: white;">
  <div class="text-center">
    <br>
    <%= image_tag('dbz.jpg')%>
    <ul class="list-inline">
      <li><%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link"%></li>
      <li><%= link_to "Biografia", pages_biografia_path, class: "navbar-wagon-item navbar-wagon-link"%></li>
      <li><%= link_to "Carrera", pages_carrera_path, class: "navbar-wagon-item navbar-wagon-link"%></li>
      <li><%= link_to "Videos", root_path, class: "navbar-wagon-item navbar-wagon-link"%></li>
      <li><%= link_to "Contact", root_path, class: "navbar-wagon-item navbar-wagon-link"%></li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag('mr.png') %>
  <% end %>
<div class="navbar-wagon-right hidden-xs hidden-sm">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
       <li> <p><%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <li><p><%= link_to "Biografia", pages_biografia_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <li><p><%= link_to "Carrera", pages_carrera_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <li><p><%= link_to "Videos", pages_videos_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <li><p><%= link_to "Contact", pages_contact_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <% if current_user %>
       <p><%= link_to "Mensajes", letters_path, class: "navbar-wagon-item navbar-wagon-link"%></p>
       <%= link_to destroy_user_session_path, method: :delete do %>
       <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
       <% end %>
       <% end %>
     </ul>
   </div>
 </div>
 <div class="navbar-wagon-item hidden-md hidden-lg">
 <div class="dropdown">
  <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
  <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
       <li> <p><%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <li><p><%= link_to "Biografia", pages_biografia_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <li><p><%= link_to "Carrera", pages_carrera_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <li><p><%= link_to "Videos", pages_videos_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <li><p><%= link_to "Contact", pages_contact_path, class: "navbar-wagon-item navbar-wagon-link"%></p></li>
       <% if current_user %>
       <p><%= link_to "Mensajes", letters_path, class: "navbar-wagon-item navbar-wagon-link"%></p>
       <%= link_to destroy_user_session_path, method: :delete do %>
       <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
       <% end %>
       <% end %>
     </ul>
 </div>
</div>
</div>